name: Go

on:
  push:
  schedule: [cron: '00 * * * *']

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Run main.go
      env:
        username: ${{ secrets.J_USERNAME }}
        password: ${{ secrets.J_PASSWORD }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        BOT_CHANNEL: ${{ secrets.BOT_CHANNEL }}
      run: |
        echo -e 'J_USERNAME=username\nJ_PASSWORD=password\nBOT_TOKEN=BOT_TOKEN\nBOT_CHANNEL=BOT_CHANNEL' > ./.env
        go run main.go
