name: Go

on:
  push:
  schedule: [cron: '10 * * * *']

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Run main.go
      with:
        J_USERNAME: ${{secrets.J_USERNAME}}
        run: |
          echo -e 'J_USERNAME= "$JUSER_NAME" \nJ_PASSWORD= ${{ secrets.J_PASSWORD }} \nBOT_TOKEN= ${{ secrets.BOT_TOKEN }} \nBOT_CHANNEL= ${{ secrets.BOT_CHANNEL }} ' > .env
          go run main.go
