name: Go

on:
  push:
  schedule: [cron: '00 * * * *']

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Run main.go
      run: |
        echo -e 'J_USERNAME=${{ secrets.J_USERNAME }}\nJ_PASSWORD=${{ secrets.J_PASSWORD }}' > ./.env
        go run main.go
