name: Go

on:
  schedule: [cron: '50 6 * * *']

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Run main.go
      run: go run main.go
